root: true
env:
  browser: true
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
  parser: '@typescript-eslint/parser'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:nuxt/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
plugins:
  - 'vue'
  - '@typescript-eslint'
